name: Push
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

env:
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  TARGET_IMAGE_NAME: "peco602/ansible-linux-docker:latest"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ env.DOCKERHUB_USERNAME }}
            password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build
        run : docker build -t ${{ env.TARGET_IMAGE_NAME }} .

      - name: Push to Docker Hub
        run : docker push ${{ env.TARGET_IMAGE_NAME }}
